# docker-compose.yml
version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'
    networks:
      - testing-net

  opencart:
    image: agridyaev/opencart:4.0.2-3-debian-12-r33
    ports:
      - '${OPENCART_PORT}:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    networks:
      - testing-net

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT}:80'
    depends_on:
      - mariadb
    networks:
      - testing-net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8090:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins_allure_results:/var/jenkins_home/workspace/Test_Project_Otus/allure-results
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - testing-net
    privileged: true

  allure-report:
    image: "frankescobar/allure-docker-service"
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: "true"
    volumes:
      - jenkins_allure_results:/app/allure-results
    networks:
      - testing-net
    depends_on:
      - jenkins

networks:
  testing-net:
    driver: bridge

volumes:
  jenkins_allure_results: